Triple DES | SHA-256 | Сплайны | Градиентный спуск: MyTcpServer Class Reference
MyTcpServer Class Reference
Public Slots
void onNewConnection ()
void onReadyRead ()
void onClientDisconnected ()
Public Member Functions
MyTcpServer (QObject *parent=nullptr)
Detailed Description
Definition at line 26 of file main_server.cpp.
Constructor & Destructor Documentation
MyTcpServer()
MyTcpServer::MyTcpServer (QObject * parent = nullptr) inline explicit
Definition at line 28 of file main_server.cpp.
References onNewConnection().
Member Function Documentation
onClientDisconnected
void MyTcpServer::onClientDisconnected () inline slot
Definition at line 76 of file main_server.cpp.
Referenced by onNewConnection().
onNewConnection
void MyTcpServer::onNewConnection () inline slot
Definition at line 40 of file main_server.cpp.
References onClientDisconnected(), and onReadyRead().
Referenced by MyTcpServer().
onReadyRead
void MyTcpServer::onReadyRead () inline slot
Definition at line 54 of file main_server.cpp.
Referenced by onNewConnection().
The documentation for this class was generated from the following file:
server/main_server.cpp