Triple DES | SHA-256 | Сплайны | Градиентный спуск: NetworkClient Class Reference
NetworkClient Class Reference
#include <networkclient.h>
Signals
void connected ()
void disconnected ()
void error (const QString &message)
void messageReceived (const QString &response)
Public Member Functions
void connectToServer (const QString &host="127.0.0.1", quint16 port=33333)
void disconnect ()
bool isConnected () const
void sendCommand (const QString &command)
void sendEncryptedAuth (const QString &login, const QString &password)
void sendEncryptedRegister (const QString &login, const QString &password)
Static Public Member Functions
static NetworkClient & instance ()
Detailed Description
Definition at line 8 of file networkclient.h.
Member Function Documentation
connected
void NetworkClient::connected () signal
connectToServer()
void NetworkClient::connectToServer (const QString & host = "127.0.0.1", quint16 port = 33333)
Definition at line 25 of file networkclient.cpp.
disconnect()
void NetworkClient::disconnect ()
Definition at line 30 of file networkclient.cpp.
disconnected
void NetworkClient::disconnected () signal
error
void NetworkClient::error (const QString & message) signal
instance()
NetworkClient & NetworkClient::instance () static
Definition at line 20 of file networkclient.cpp.
References instance().
Referenced by instance().
isConnected()
bool NetworkClient::isConnected () const
Definition at line 34 of file networkclient.cpp.
messageReceived
void NetworkClient::messageReceived (const QString & response) signal
Referenced by sendCommand().
sendCommand()
void NetworkClient::sendCommand (const QString & command)
Definition at line 38 of file networkclient.cpp.
References messageReceived().
Referenced by sendEncryptedAuth(), and sendEncryptedRegister().
sendEncryptedAuth()
void NetworkClient::sendEncryptedAuth (const QString & login, const QString & password)
Definition at line 49 of file networkclient.cpp.
References s_clientTdes, and sendCommand().
sendEncryptedRegister()
void NetworkClient::sendEncryptedRegister (const QString & login, const QString & password)
Definition at line 54 of file networkclient.cpp.
References s_clientTdes, and sendCommand().
The documentation for this class was generated from the following files:
client/networkclient.h
client/networkclient.cpp